name: tolosat-tudatpy
channels:
  - conda-forge
  - tudat-team
dependencies:
  - tudatpy
  - matplotlib
  - scipy
  - pandas
  - plotly
  - pyproj
  - tqdm
  - sgp4
  - astropy
#  - pip:
#      - tle-tools

#  if this doesn't work comment out
#  - pip:
#      - tle-tools
